// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBgw4813T-WC4lM2dM-lx7SzAeHIRfW5U',
    appId: '1:62694469698:web:f6eebf1cb2c21b14a3fddb',
    messagingSenderId: '62694469698',
    projectId: 'app-cea-simulados',
    authDomain: 'app-cea-simulados.firebaseapp.com',
    storageBucket: 'app-cea-simulados.firebasestorage.app',
    measurementId: 'G-D46BL5X41J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKp8IbIkf3oahLxKRasbGnnzgL-tXEU-E',
    appId: '1:62694469698:android:a8cc5829f477528da3fddb',
    messagingSenderId: '62694469698',
    projectId: 'app-cea-simulados',
    storageBucket: 'app-cea-simulados.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCghVTpfQbWTUny8eauX_Nam8NsTRNc188',
    appId: '1:62694469698:ios:f677d665c46d8db7a3fddb',
    messagingSenderId: '62694469698',
    projectId: 'app-cea-simulados',
    storageBucket: 'app-cea-simulados.firebasestorage.app',
    iosBundleId: 'com.example.cea_app', // <-- LINHA CORRIGIDA
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCghVTpfQbWTUny8eauX_Nam8NsTRNc188',
    appId: '1:62694469698:ios:f677d665c46d8db7a3fddb',
    messagingSenderId: '62694469698',
    projectId: 'app-cea-simulados',
    storageBucket: 'app-cea-simulados.firebasestorage.app',
    iosBundleId: 'com.example.cea_app', // <-- LINHA CORRIGIDA
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBgw4813T-WC4lM2dM-lx7SzAeHIRfW5U',
    appId: '1:62694469698:web:a795831f60c765b9a3fddb',
    messagingSenderId: '62694469698',
    projectId: 'app-cea-simulados',
    authDomain: 'app-cea-simulados.firebaseapp.com',
    storageBucket: 'app-cea-simulados.firebasestorage.app',
    measurementId: 'G-R7LYC54VV2',
  );
}
